{"name": "Login attempt with invalid credentials", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "@allure.step(\"Setup and teardown for user creation: create a new user and provide credentials\")\n    @pytest.fixture\n    def create_user():\n        user_data = generate_user_data()\n        response = requests.post(data.Url.REGISTER_URL, json=user_data)\n>       access_token = response.json()[\"accessToken\"]\nE       KeyError: 'accessToken'\n\nconftest.py:13: KeyError"}, "start": 1725645482589, "stop": 1725645482589, "uuid": "e37622f2-f561-4d71-a179-14ca57304371", "historyId": "4f9289388c7e9be08c279b8f5a5d888d", "testCaseId": "4f9289388c7e9be08c279b8f5a5d888d", "fullName": "tests.test_user_login.TestUserLoginAPI#test_login_user_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLoginAPI"}, {"name": "host", "value": "Elenas-MacBook-Air.local"}, {"name": "thread", "value": "24359-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}